
// To see the assembly code generated by the C compiler, we can use the. -s option on the command line:
// linux> gcc -Og -s mstore.c
// This will cause GCC to run the compiler, generating an assembly file mstore.s
// Can be viewed, code as a set of instructions

// If we use the -c command-line option, GCC will both compile and assemble the code (assembler generates an object-code file)
// linux> gcc -Og -c mstore.c
// This will generate an object-code file.mstore.o that is in binary format and hence cannot be viewed directly. 
// 53 48 89 d3 e8 00 00 00 00 48 89 03 5b c3

// Dissasemble, - generate assembly code from machine code (to inspect the contents of machine-code files)
// With Linux systems, the program OBJDUMP (for "object dump") can be used given -d command-line flag:
// linux> objdump -d mstore.o

// Generating executable code requires running a linker on the set of object-code files, 
// one of which must contain a function main
// linux> gee -Og -o prog main.c mstore.c
// Resulting file prog contains machine code for the procedures we provided 
// plus code used to start/terminate the program, interact with the operating system.

// We can dissasemble prog file
// linux> objdump -d mstore.o

#include <stdio.h>
void multstore(long, long, long *);

int main() {
    long d;
    multstore(2, 3, &d); 
    printf("2 * 3 --> %ld\n", d); 
    return 0;
}
long mult2(long a, long b) {
    long s = a * b;
    return s;
}

